title: cState Test
buildFuture: true
defaultContentLanguage: fr
languageCode: fr
baseURL: https://cstate.deniau.co/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: true
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 02/01 15:04
  down: "#e60000"
  systems:
    - name: Pare-feu
      category: Site A
    - name: Pare-feu
      category: Site B
  dateFormat: Mon 2 January 2006 at 15:04
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Site A
      description: Services spécifiques du site A
      closed: false
    - name: Site B
      description: Services spécifiques du site B
      closed: false
    - name: Uncategorized
      untitled: true
  description: Nous monitorons l'état de nos services et indiquons ici les
    interruptions et plages de maintenance.
  enableCustomHTML: true
  useLargeHeaderDesign: false
