title: cState Test
buildFuture: true
defaultContentLanguage: fr
languageCode: fr
baseURL: https://cstate.deniau.co/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: true
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 02/01 15:04
  down: "#e60000"
  systems:
    - name: Gateway
      category: North Coast
    - name: Backup Gateway
      category: North Coast
    - name: Website
      description: The web frontend for the application.
      category: Uncategorized
      link: https://example.com/
    - name: API
      description: The guts of the application.
      category: Uncategorized
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Uncategorized
  dateFormat: Mon 2 January 2006 at 15:04
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: North Coast
      description: The main servers are located here.
      closed: true
    - name: Empty Category
    - name: Uncategorized
      untitled: true
  description: Nous monitorons l'état de nos services et indiquons ici les
    interruptions et plages de maintenance.
  enableCustomHTML: true
  useLargeHeaderDesign: false
